name: Deploy to Surge

on:
  push:
    branches:
      - main   # or the name of your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install and publish to Surge
      run: |
        npm install -g surge
        surge --project ./ --domain nice-amusement.surge.sh
      env:
        SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
